In [1]:
import pandas as pd

In [2]:
na_values = ['NaN','Na','N/A']
df = pd.read_csv('cleaned_data_before_numeric_change.csv',na_values=na_values)

In [3]:
df

,id,host_id,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,property_type,room_type,...,bathrooms_text,beds,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month
0,772195193586734462,139504671,57.0,f,2.0,t,t,Indre By,Private room in rental unit,Private room,...,1 shared bath,1.0,1320.467531,5,12,0,0,4.818525,f,0.733238
1,993508926988263521,540024469,100.0,f,1.0,t,f,Amager st,Entire rental unit,Entire home/apt,...,1 bath,1.0,860.000000,2,20,25,9,4.670000,f,3.330000
2,973046361084511805,413314931,57.0,f,1.0,t,t,Amager Vest,Entire rental unit,Entire home/apt,...,1 bath,1.0,1000.000000,2,60,107,7,4.860000,f,3.750000
3,52551491,36416123,48.0,f,1.0,t,t,Vesterbro-Kongens Enghave,Entire condo,Entire home/apt,...,1 bath,1.0,1200.000000,2,7,178,16,5.000000,f,0.590000
4,723099448414722172,5049349,79.0,t,3.0,t,t,Vesterbro-Kongens Enghave,Entire condo,Entire home/apt,...,1 bath,3.0,1400.000000,2,30,118,16,4.940000,f,1.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18226,899314240743700953,516545031,92.0,f,1.0,f,t,Vesterbro-Kongens Enghave,Entire rental unit,Entire home/apt,...,1 bath,1.0,1320.467531,2,7,0,6,4.830000,t,0.930000
18227,894209151571063412,87341967,100.0,t,1.0,t,t,Frederiksberg,Entire rental unit,Entire home/apt,...,1 bath,1.0,1320.467531,1,365,0,11,4.820000,t,1.530000
18228,882414557986654201,378586472,33.0,f,1.0,t,t,Amager Vest,Entire rental unit,Entire home/apt,...,1 bath,3.0,1320.467531,3,365,0,0,4.818525,f,0.733238
18229,50437911,90546144,94.0,t,1.0,t,t,Vesterbro-Kongens Enghave,Entire rental unit,Entire home/apt,...,1 bath,1.0,1873.000000,4,60,222,27,4.960000,f,0.910000
18230,899770214952158073,473758988,63.0,f,1.0,t,t,Nørrebro,Entire rental unit,Entire home/apt,...,1 bath,1.0,1320.467531,7,1125,0,4,5.000000,f,0.570000

Feature engineering price intervals.

In [4]:
num_bins = [0,100,200,500,800,1000,2000,10000,100000]

df['price_intervals'] = pd.cut(df['price'],bins=num_bins)

In [5]:
df.isnull().sum()

id                           0
host_id                      0
host_acceptance_rate         0
host_is_superhost            0
host_total_listings_count    0
host_has_profile_pic         0
host_identity_verified       0
neighbourhood_cleansed       0
property_type                0
room_type                    0
accommodates                 0
bathrooms_text               0
beds                         0
price                        0
minimum_nights               0
maximum_nights               0
availability_365             0
number_of_reviews            0
review_scores_rating         0
instant_bookable             0
reviews_per_month            0
price_intervals              0
dtype: int64

Taking parameters i wish to check for which is property_type, room_type, bathrooms_text, beds, price

In [6]:
selected_columns = ['neighbourhood_cleansed','property_type', 'room_type', 'bathrooms_text','price_intervals']

selection_df = df[selected_columns].copy()

In [7]:
selection_df

,neighbourhood_cleansed,property_type,room_type,bathrooms_text,price_intervals
0,Indre By,Private room in rental unit,Private room,1 shared bath,"(1000, 2000]"
1,Amager st,Entire rental unit,Entire home/apt,1 bath,"(800, 1000]"
2,Amager Vest,Entire rental unit,Entire home/apt,1 bath,"(800, 1000]"
3,Vesterbro-Kongens Enghave,Entire condo,Entire home/apt,1 bath,"(1000, 2000]"
4,Vesterbro-Kongens Enghave,Entire condo,Entire home/apt,1 bath,"(1000, 2000]"
...,...,...,...,...,...
18226,Vesterbro-Kongens Enghave,Entire rental unit,Entire home/apt,1 bath,"(1000, 2000]"
18227,Frederiksberg,Entire rental unit,Entire home/apt,1 bath,"(1000, 2000]"
18228,Amager Vest,Entire rental unit,Entire home/apt,1 bath,"(1000, 2000]"
18229,Vesterbro-Kongens Enghave,Entire rental unit,Entire home/apt,1 bath,"(1000, 2000]"
18230,Nørrebro,Entire rental unit,Entire home/apt,1 bath,"(1000, 2000]"

Taking vectorizer from sklearn. Using it do split data into documents and calculate TF and IDF and make vectors from each documents.

In [8]:
documents = selection_df['neighbourhood_cleansed'] + " " + selection_df['property_type'] + ' ' + selection_df['room_type'] + ' ' + selection_df['bathrooms_text'] + ' ' + selection_df['price_intervals'].astype(str)
documents

0        Indre By Private room in rental unit Private r...
1        Amager st Entire rental unit Entire home/apt 1...
2        Amager Vest Entire rental unit Entire home/apt...
3        Vesterbro-Kongens Enghave Entire condo Entire ...
4        Vesterbro-Kongens Enghave Entire condo Entire ...
                               ...
18226    Vesterbro-Kongens Enghave Entire rental unit E...
18227    Frederiksberg Entire rental unit Entire home/a...
18228    Amager Vest Entire rental unit Entire home/apt...
18229    Vesterbro-Kongens Enghave Entire rental unit E...
18230    Nørrebro Entire rental unit Entire home/apt 1 ...
Length: 18231, dtype: object

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(documents)

In [10]:
tfidf_matrix.shape

(18231, 72)

In [11]:
#For computing cosine between vectors
from sklearn.metrics.pairwise import linear_kernel

In [12]:
def get_recommendations(neighbourhood, property_type, room_type, bathrooms_text, price_interval):
    inputt = neighbourhood + " " + property_type + " " + room_type + " " + bathrooms_text + " " + price_interval
    
    input_vector = tfidf.transform([inputt])

    similarity_scores = linear_kernel(input_vector, tfidf_matrix)

    top_indices = similarity_scores.argsort()[0][::-1][:10]

    top_similar_rental_units = df.iloc[top_indices]
    
    return top_similar_rental_units

In [13]:
def get_recommendations2(user_input):
    
    input_vector = tfidf.transform([user_input])

    similarity_scores = linear_kernel(input_vector, tfidf_matrix)

    top_indices = similarity_scores.argsort()[0][::-1][:10]

    top_similar_rental_units = df.iloc[top_indices]
    
    return top_similar_rental_units

In [37]:
pd.set_option("display.max_columns", 40)

In [42]:
get_recommendations('indre','Private room in rental unit','Private','1','500')

,id,host_id,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,property_type,room_type,accommodates,bathrooms_text,beds,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,price_intervals
17445,8563559,10887109,99.0,t,1.0,t,t,Indre By,Private room in rental unit,Private room,2,1 private bath,1.0,523.0,2,1125,219,315,4.880000,f,3.150000,"(500, 800]"
15928,14737946,44154045,47.0,f,4.0,t,t,Indre By,Private room in rental unit,Private room,2,1 private bath,1.0,706.0,5,21,170,65,4.780000,f,0.730000,"(500, 800]"
1661,39012290,8916473,100.0,t,4.0,t,t,Indre By,Private room in rental unit,Private room,2,1 private bath,1.0,664.0,3,1125,5,16,5.000000,f,0.320000,"(500, 800]"
15227,20376992,15075072,99.0,f,2.0,t,t,Indre By,Private room in rental unit,Private room,3,1 private bath,1.0,428.0,3,1125,140,272,4.690000,f,3.540000,"(200, 500]"
5320,866563269205625041,359510710,26.0,f,1.0,t,f,Indre By,Private room in rental unit,Private room,2,1 private bath,2.0,490.0,3,365,88,1,5.000000,f,0.200000,"(200, 500]"
10559,894617708996789040,371004204,100.0,f,3.0,t,f,Indre By,Private room in rental unit,Private room,1,1 bath,1.0,529.0,5,365,27,10,4.800000,f,1.670000,"(500, 800]"
86,919613195329293559,494320140,24.0,f,1.0,t,t,Indre By,Private room in rental unit,Private room,2,1 bath,1.0,800.0,1,365,265,1,5.000000,f,0.240000,"(500, 800]"
16061,1024018033019123952,352662638,0.0,f,2.0,t,t,Indre By,Private room in rental unit,Private room,1,1 bath,1.0,600.0,7,30,62,0,4.818525,f,0.733238,"(500, 800]"
16051,971911383594464377,533480916,97.0,f,5.0,f,t,Indre By,Private room in rental unit,Private room,2,1 bath,1.0,744.0,1,365,269,1,5.000000,f,0.290000,"(500, 800]"
12388,5486840,27406722,78.0,t,1.0,t,t,Indre By,Private room in rental unit,Private room,2,1 bath,1.0,550.0,3,60,55,103,4.870000,f,1.060000,"(500, 800]"

In [43]:
get_recommendations('indre','Private','1','shared','1000')

,id,host_id,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,property_type,room_type,accommodates,bathrooms_text,beds,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,price_intervals
0,772195193586734462,139504671,57.000000,f,2.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,5,12,0,0,4.818525,f,0.733238,"(1000, 2000]"
16338,914975462637560323,40049506,40.000000,f,3.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,5,21,0,2,4.500000,f,0.370000,"(1000, 2000]"
11099,35839191,178320,100.000000,f,3.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,2,7,0,23,4.870000,f,0.420000,"(1000, 2000]"
10803,38667633,46445934,0.000000,f,1.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1200.000000,2,6,87,2,4.000000,f,0.040000,"(1000, 2000]"
10458,51568169,43947147,71.554308,f,2.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,2,1125,0,17,5.000000,f,0.590000,"(1000, 2000]"
10429,25851499,194237765,71.554308,f,3.0,t,t,Indre By,Private room in rental unit,Private room,1,1 shared bath,1.0,1320.467531,1,1125,0,15,4.870000,t,0.220000,"(1000, 2000]"
17695,918928139452421475,330805913,0.000000,f,1.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,1,25,0,0,4.818525,f,0.733238,"(1000, 2000]"
8268,52021443,31741086,60.000000,f,2.0,t,t,Indre By,Private room in rental unit,Private room,1,1 shared bath,1.0,1320.467531,2,16,0,3,5.000000,f,0.110000,"(1000, 2000]"
8213,49336526,20053611,71.554308,f,2.0,t,t,Indre By,Private room in rental unit,Private room,2,1 shared bath,1.0,1320.467531,2,365,0,1,5.000000,f,0.030000,"(1000, 2000]"
15306,902095588134517281,40049506,40.000000,f,3.0,t,t,Indre By,Private room in rental unit,Private room,1,1 shared bath,1.0,1320.467531,5,93,0,0,4.818525,f,0.733238,"(1000, 2000]"

In [16]:
get_recommendations('nørrebro','Private','1','shared','200')

,id,host_id,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,property_type,room_type,...,beds,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,price_intervals
17743,49251563,12454263,100.0,f,4.0,t,t,Nørrebro,Private room,Private room,...,1.0,444.0,30,100,31,19,4.630000,f,0.660000,"(200, 500]"
17654,1218328,6251797,0.0,f,1.0,t,f,Nørrebro,Private room in rental unit,Private room,...,1.0,500.0,1,1125,56,191,4.800000,f,1.480000,"(200, 500]"
11392,773226986315721516,2038200,89.0,f,3.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,321.0,4,90,20,2,4.500000,f,2.000000,"(200, 500]"
16118,982449915176492479,168723549,0.0,f,11.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,500.0,1,365,269,0,4.818525,f,0.733238,"(200, 500]"
4591,7353832,38533050,100.0,t,2.0,t,f,Nørrebro,Private room in rental unit,Private room,...,1.0,474.0,4,30,15,24,4.830000,f,0.260000,"(200, 500]"
7642,33461634,252097959,100.0,f,2.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,385.0,2,14,30,45,4.670000,f,0.850000,"(200, 500]"
9496,818601992672184504,17818905,82.0,f,2.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,500.0,1,365,162,10,4.300000,f,0.950000,"(200, 500]"
14437,23811209,791129,52.0,t,6.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,319.0,30,1125,31,12,4.920000,f,0.170000,"(200, 500]"
13591,887461136094251162,31226452,19.0,f,4.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,400.0,3,365,50,4,5.000000,f,0.550000,"(200, 500]"
14047,34835494,13857263,90.0,t,1.0,t,t,Nørrebro,Private room in rental unit,Private room,...,1.0,300.0,1,30,45,178,4.780000,f,3.180000,"(200, 500]"

In [48]:
get_recommendations2("indre by price 1000")

,id,host_id,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,property_type,room_type,accommodates,bathrooms_text,beds,price,minimum_nights,maximum_nights,availability_365,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,price_intervals
16154,19755571,26302109,25.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,2,1 bath,2.0,1500.000000,3,20,83,9,5.000000,f,0.120000,"(1000, 2000]"
5651,50306346,9480538,100.000000,f,2.0,t,t,Indre By,Entire home,Entire home/apt,6,1 bath,4.0,1629.000000,3,42,2,11,4.730000,f,0.370000,"(1000, 2000]"
11547,857230985895207321,19614750,47.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,2,1 bath,1.0,1750.000000,3,365,78,6,5.000000,f,0.790000,"(1000, 2000]"
16904,910173855396155528,140752313,60.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,4,1 bath,1.0,1999.000000,2,15,364,3,4.330000,f,0.720000,"(1000, 2000]"
6037,923725784314896500,522509674,100.000000,f,1.0,f,t,Indre By,Entire home,Entire home/apt,6,1 bath,6.0,2000.000000,5,12,76,0,4.818525,f,0.733238,"(1000, 2000]"
5090,894535740374605667,311940082,67.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,4,1 bath,3.0,1750.000000,3,365,164,3,5.000000,f,0.470000,"(1000, 2000]"
13252,957171981556580049,63479454,0.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,5,1 bath,5.0,1800.000000,3,1125,0,0,4.818525,f,0.733238,"(1000, 2000]"
14887,26509594,199375729,0.000000,f,1.0,t,f,Indre By,Entire home,Entire home/apt,5,1 bath,5.0,1400.000000,4,1125,0,2,5.000000,f,0.030000,"(1000, 2000]"
10124,1005583309077889843,2786061,88.000000,f,1.0,t,t,Indre By,Entire home,Entire home/apt,4,1 bath,2.0,1029.000000,2,30,1,12,4.670000,f,6.670000,"(1000, 2000]"
17090,528914,2598525,71.554308,f,3.0,t,t,Indre By,Entire home,Entire home/apt,5,1 bath,4.0,1320.467531,5,99,0,10,5.000000,f,0.070000,"(1000, 2000]"